### ISSUE TITLE
error: browsing HAMT dirs extremely slow 

### ISSUE THREAD

**Issue by lidel** [ipfs/bifrost-gateway#21]
Opening `/ipns/en.wikipedia-on-ipfs.org/wiki/` requires enumerating a HTML-sharded UnixFS directory with ~20 milion entries. 

This means multiple blocks need to be fetched before we can find the CID of `/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/index.html`

## How to reproduce

Try browsing `http://localhost:8080/ipfs/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/wiki/` and then going to some pages that are not cached on saturn.

OR `bafybeiggvykl7skb2ndlmacg2k5modvudocffxjesexlod2pfvg5yhwrqm` which is a directory with 10k of JPGs.

## Potential fixes

sane:
- basic LRU cache for blocks may help #15  
- maybe additional cache for blocks that belong to unixfs HAMT nodes?

insane:
- cheat, and delegate `ResolvePath` of expensive HAMTs to `/api/v0/resolve` 
  - less insane: race `ResolvePath` backed by local LRU cache vs remote RPC and use whichever returns faster result

**Comment by aschmahmann** [comment]
IMO we shouldn't spend too much time worrying about this. Everyone was warned how slow this was going to be, we're better off spending our time doing things we want for M >0.2.

For example:
1. Sessions so caboose can choose to leverage them in deciding where to route requests if they want
2. Refactoring the Gateway API code so it processes full requests instead of partial ones (i.e. is higher level)
3. Prototyping and cat wrangling on the HTTP API that will allow for larger requests

Ultimately we can deal with a lot of Saturn slowness and/or misbehavior by sticking optimized blockstore caching here. However, IMO this shouldn't be where we start as any issues we paper over here are going to be ones that show up for other Saturn clients (e.g. browser nodes) anyway. While ultimately we're going to have to pull out any available tricks to make this as fast and efficient as we can for ipfs.io I just don't want to start by masking systemic issues.

**Comment by lidel** [comment]
With block cache added in https://github.com/ipfs/bifrost-gateway/pull/15 it is no longer excruciating :+1: 
Good enough, let's focus on CARs.
